# Generated by Django 5.1.5 on 2025-02-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('foto', models.FileField(blank=True, upload_to='artist/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('foto', models.FileField(blank=True, null=True, upload_to='director/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Podpiska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Подписка')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('poster', models.FileField(blank=True, null=True, upload_to='posters', verbose_name='Постер')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рэйтинг')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('artist', models.ManyToManyField(to='kino42.artist')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino42.country', verbose_name='Страна')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino42.director', verbose_name='Режиссер')),
                ('genre', models.ManyToManyField(to='kino42.genre')),
                ('podpiska', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino42.podpiska', verbose_name='Подписка')),
            ],
        ),
    ]
