# Generated by Django 5.1.5 on 2025-02-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino42', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanse', models.IntegerField(default=1000)),
                ('podpiska', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='kino42.podpiska')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
